version: "3.9"
services:
  api-gateway:
    build: ../api-gateway
    env_file: ./.env
    ports: ["8080:8080"]
    depends_on:
      - disease-detection
      - yield-prediction
      - recommendation
      - notification
      - weather
      - user-management
      - whatsapp-bot
      - telegram-bot
      - mongodb
      - redis

  disease-detection:
    build: ../services/disease-detection
    env_file: ./.env
    ports: ["8001:8001"]
    volumes:
      - ../services/disease-detection/models:/app/models:ro

  yield-prediction:
    build: ../services/yield-prediction
    env_file: ./.env
    ports: ["8002:8002"]
    volumes:
      - ../services/yield-prediction/models:/app/models:ro

  recommendation:
    build: ../services/recommendation
    env_file: ./.env
    ports: ["8003:8003"]

  notification:
    build: ../services/notification
    env_file: ./.env
    ports: ["8004:8004"]

  weather:
    build: ../services/weather
    env_file: ./.env
    ports: ["8005:8005"]

  user-management:
    build: ../services/user-management
    env_file: ./.env
    ports: ["8006:8006"]

  whatsapp-bot:
    build: ../services/whatsapp-bot
    env_file: ./.env
    ports: ["8011:8011"]
    depends_on: [api-gateway, redis]

  telegram-bot:
    build: ../services/telegram-bot
    env_file: ./.env
    ports: ["8012:8012"]
    depends_on: [api-gateway, redis]

  web-app:
    build: ../web-app
    env_file: ./.env
    ports: ["3000:3000"]
    depends_on: [api-gateway]

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    ports: ["6379:6379"]

volumes:
  mongo_data:
